---
- name: Respaldo de configuración del router
  hosts: router
  gather_facts: no

  tasks:
    - name: Ejecutar "show running-config"
      ios_command:
        commands: show running-config
      register: running_config_output

    - name: Guardar la configuración en un archivo
      copy:
        content: "{{ running_config_output.stdout[0] }}"
        dest: "/path/al/directorio/backup_running_config.txt"
